import { StyleSheet } from 'react-native'
import { colors } from '../../constants/colors'
import { sizes } from '../../constants/sizes'

export default styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.fondoClaro,
    },
    containerRenderCanciones:{
        flex: 1,
        backgroundColor: colors.fondoClaro,
    },
    iconDeseleccionar:{
        position: 'absolute',
        top: 10,     
        right: 10,    
    },
    containerCancion: {
        flexDirection: 'row',
        padding: 10,
        borderWidth: 1,
        borderColor: colors.violeta,
        borderRadius: 10,
        backgroundColor: colors.blanco,
        alignItems: 'center',
        width: '100%',
        marginTop: 15,
    },
    portadaMusica: {
        resizeMode: 'contain',
        borderRadius: 10,
        height: 100,
        width: 100,
    },
    tituloAutor: {
        color: colors.negro,
        fontSize: 20,
    },
    infoCancion: {   
        alignItems: 'center',
        flexDirection: 'column',
        flex: 1,
    },
    input: {
        fontSize: 18,
        marginTop: 10,
        backgroundColor: colors.blanco,
        height: '40%',
        textAlignVertical:'top',
        borderRadius: 15,
        padding: 15,
        borderColor: colors.turquesa,
        borderWidth: 1,
    },
    ekoContainer: {
        flexDirection: 'row',
    },
    imagenDePerfil: {
        width: 60,
        height: 60,
        borderRadius: 25,
    },
    ekoContenido: {
        flex: 1,
        marginLeft: 15,
        justifyContent: 'center',
    },
    nombreUnico: {
        fontSize: 18,
    },
    nombre: {
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.violeta,
    },
    botonSeleccionarCancion: {
        backgroundColor: colors.turquesa,
        padding: 10,
        borderRadius: 10,
        shadowColor: colors.blanco,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 4,
        elevation: 5,
        marginTop: 15,
        alignSelf: 'center', 
        maxWidth: 200, 
    },
    textoBoton: {
        color: colors.negro,
        fontSize: sizes.botones,
        textAlign: 'center',
    },
    botonEkear: {
        backgroundColor: colors.turquesa,
        padding: 10,
        borderRadius: 10,
        shadowColor: colors.blanco,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 4,
        elevation: 5,
        marginTop: 25,
        alignSelf: 'center', 
        marginBottom: 25,
    },
    containerGeneralCancion: {
        width: '100%',
        backgroundColor: colors.fondoClaro,
        flex: 1,
    },
    viewGeneral: {
        flex: 1,
        alignItems: 'center',
        backgroundColor: colors.fondoClaro,
    },
    viewGeneral: {
        flex: 1,
        alignItems: 'center',
        backgroundColor: colors.fondoClaro,
    },
    viewBusqueda: {
        backgroundColor: colors.fondoClaro,
        flexDirection: 'row',
        paddingHorizontal: 20,
    },
    barraBusqueda: {
        paddingVertical: 10,
        paddingHorizontal: 20,
        margin: 10,
        width: '100%',
        borderRadius: 20,
        backgroundColor: colors.blanco,
        borderColor: colors.violeta,
        fontSize: sizes.inputs,
        borderWidth: 1,
        paddingRight: 45,
    },
    iconoLupa: {
        position: 'absolute',
        right: 45,
        top: '50%', 
        transform: [{ translateY: -15 }],
    },
    containerGeneral: {
        width: '100%',
        backgroundColor: colors.fondoClaro,
        flex: 1,
    },
    container: {
        flexDirection: 'row',
        flex: 1,
        padding: 10,
        borderWidth: 1,
        borderColor: colors.violeta,
        borderRadius: 10,
        margin: 8,
        backgroundColor: colors.blanco,
        alignItems: 'center',
    },
    perfil: {   
        alignItems: 'center',
        flexDirection: 'column',
        flex: 1,
    },
    username: {
        fontSize: 16,
        color: colors.turquesa,
    },
    usuarioArroba: {
        color: colors.negro,
        fontSize: 16,
    },
    portadaMusica: {
        aspectRatio: 1,
        resizeMode: 'cover',
        borderRadius: 10,
        height: 50,
    },
})